### PR TITLE
Push changed built assets

### LINKED ISSUE #4: Let tests.yml push back to the repo on merges

### PR DESCRIPTION
**Pull request by mlocati**
Close #4

### CODE REVIEW

**Comment by szepeviktor** [comment]
This PR shows that this project does not include viktor resources.
I have 3-4 thoughts.
But I am not onboard!

**Comment by mlocati** [comment]
> this project does not include viktor resources.

I'm sorry I don't understand... what are those "viktor resources"?

**Comment by szepeviktor** [comment]
Viktor exercises Total Control©️ over every byte. So I spend countless hours cleaning up each byte.

1. The source of `build` is the Internet, so we need a human/machine to check that the changes are okay.
2. UNICODE changes are [very-very-very rare](https://www.unicode.org/history/publicationdates.html) So I would have viktor look at each change set.
3. It should be a separate workflow
4. Make it a PR (`gh pr create`) so other workflows will check it.
5. `if:` is too long
6. Never have a robot commit in the name of Michele! (set up a 🤖 unipoint-bot)

You can see that all these take viktor-resources.

**Comment by mlocati** [comment]
Yep, I agree. See #25

**Pull request merged**
