### PR TITLE
Let's create a new problem!

### PR DESCRIPTION
**Pull request by szepeviktor**
☣️ Not a PR.

### CODE REVIEW

**Comment by mlocati** [comment]
Yep, pretty useless ATM, since we don't have any dependency yet 😉

**Comment by szepeviktor** [comment]
No problems 😢 😢 😭 

But I could investigate why PHP setup takes 2+ minutes.

image

**Comment by szepeviktor** [comment]
It should take 7 seconds!

image

**Comment by mlocati** [comment]
Is maybe setup-php taking a lot of time when it installs php-cs-fixer?

**Comment by szepeviktor** [comment]
> it installs php-cs-fixer?

Yes, I'm opening an issue ...

**Comment by szepeviktor** [comment]
https://github.com/shivammathur/setup-php/issues/773 👀

**Comment by szepeviktor** [comment]
Michele broke the Internet again 🙃 

In my laboratory installing php-cs-fixer takes ~1 second.
https://github.com/szepeviktor/byte-level-care/actions/runs/6684954105/job/18162746337?pr=79#step:2:15

**Comment by szepeviktor** [comment]
With the above commit it is 7 seconds!

Investigating ... 🔎

**Comment by szepeviktor** [comment]
It is the PHP setup action! Its latest version has a problem.

**Comment by szepeviktor** [comment]
It run in 2 minutes in my repo too.
https://github.com/szepeviktor/byte-level-care/pull/79/files
Viktor is very conservative with software. I let the messes find bugs. Then I upgrade.

**Pull request closed without merging**
